/**
 * This file holds the common DS shared by the system.
 */
#ifndef _COMMON_DS_H_
#define _COMMON_DS_H_

#include "config.h"


/**
 * @brief      The message structure for the priority queue.
 */
struct msg_t {
int32_t priority;
uint8_t data[MSG_LEN];

};

/**
 * @brief      Events generated by Q.
 */
enum Q_EVT {
    ALMOST_FULL=0,
    ALMOST_EMPTY
};



#endif